#129 - Optimize scaling of plugin installation trends
jenkins-infra/plugin-site pull request #402
Opened 2020-10-16 19:20 UTC by ARUNMOHANRAJ471

Related to issue #129 

Summary of this pull request: 
I have added an logic to dynamically set the y-axis values to improve the look and feel of the graphs which can now helps us visualize the installation trends better.

**gerrit-verify-status-reporter Plugin:**
Before:
![image](https://user-images.githubusercontent.com/24914964/96299966-7565e580-1012-11eb-9d58-f7efded6d99b.png)

After:
![image](https://user-images.githubusercontent.com/24914964/96300078-9af2ef00-1012-11eb-8e34-ea12d4c198d3.png)

2020-10-17 03:40 UTC, halkeye commented
My concern is it can mislead how many installs are being represented. A graph showing data should always have the same scale as another graph showing the exact same data.

But I'll leave it for @oleg-nenashev and @zbynek

2020-10-17 20:52 UTC, zbynek requested changes
I think we should keep min value as 0 for all plugins. Otherwise this will look like big changes are happening for plugins with nearly constant number of installs.

@halkeye the max value was different for each plugin already, this just makes it more predictable.

2020-10-19 04:16 UTC, ARUNMOHANRAJ471 commented
Hi @zbynek ,@halkeye If we have the min value as 0 for all the plugins the graph will look the same as like in production. If the objective of the chart is to display plugin installation trends to user, having a min of 0 in y axis will not help the user to get the insight as the changes will be mildly visible.

In this case, as suggested by @zbynek in the issue #129 , we can display the trends as a sparkline chart and can show number of weekly/monthly downloads like in npm.

Pls share your views.

2020-10-20 06:54 UTC, halkeye commented
I still don't think the graph solves anything if the scale changes each time its visible.

~Can you mock up what the sparkline would look like?~ I just went and looked at the npm version. I like it because its clear whats going on, but it has the same issue

1-5 downloads a week
![image](https://user-images.githubusercontent.com/110087/96550783-27492000-1266-11eb-97fc-bb1a87c10309.png)

700k downloads a week
![image](https://user-images.githubusercontent.com/110087/96550824-39c35980-1266-11eb-9508-f3390ef8e93a.png)

They don't look different. So what is the goal of the graph? its been there longer than I have been involved. The NPM version works great if the goal is to see if anything drastic changes in the number of downloads. If thats the goal, then The current implementation is fine.

@ARUNMOHANRAJ471 can you grab a screenshot of a small plugin and a large plugin like I did above?

2020-10-28 01:18 UTC, zbynek commented
[Mailer](https://plugins.jenkins.io/mailer/)
![image](https://user-images.githubusercontent.com/1105305/97377226-d49fe180-18bf-11eb-88ea-501db3001a19.png)

[Last changes](https://plugins.jenkins.io/last-changes)
![image](https://user-images.githubusercontent.com/1105305/97377376-2ba5b680-18c0-11eb-97b3-b1362314e2b2.png)

[Parallels Desktop](https://plugins.jenkins.io/parallels-desktop/)
![image](https://user-images.githubusercontent.com/1105305/97377654-d0c08f00-18c0-11eb-9dee-f393021e21e8.png)

2020-10-28 06:07 UTC, halkeye commented
It definitely highlight the changes a lot more but won't be great at showing the differences between plugins.

I'm honestly not sure what the goal of the graph is, so lets move forward with the new scale and see if anyone complains.

2020-10-28 07:12 UTC, zbynek approved these changes

2020-10-28 07:12 UTC, merged

2020-10-30 18:28 UTC, daniel-beck reviewed
This should be reverted or overhauled. Not including Y=0 is actively detrimental when trying to understand the graphs.

2020-10-30 18:28 UTC, daniel-beck commented on src/components/LineChart.jsx
> -    if (lastValue > 5000) minValue = 0;
👎 Removing this is a bad idea, as the graphs are now very misleading. I've been so confused about the insane jumps in popularity in some plugins — how did https://plugins.jenkins.io/git-parameter/ **double** its installations!? Wait… it didn't. It's like +10% and graphs are now terrible.

If there is no easily visible difference in numbers if you don't show Y=0, then there are no changes that matter. The way we collect this data is unreliable in the first place, so if you want to discern differences between a few percentages, you're already doing it wrong.

2020-10-30 21:23 UTC, daniel-beck commented on src/components/LineChart.jsx
> -    if (lastValue > 5000) minValue = 0;
Amended in #445.